name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/brunorodmoreira/cicd-vtex-cli-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    env:
      VTEX_ACCOUNT: ${{ secrets.VTEX_ACCOUNT }}
      VTEX_APP_KEY: ${{ secrets.VTEX_APP_KEY }}
      VTEX_APP_TOKEN: ${{ secrets.VTEX_APP_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create VTEX Session
        run: create-session --account $VTEX_ACCOUNT --appkey $VTEX_APP_KEY --apptoken $VTEX_APP_TOKEN

      - name: vtex publish
        run: vtex publish -y

      - name: vtex deploy
        run: yes Y | vtex deploy -f
