name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/brunorodmoreira/cicd-vtex-cli-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create VTEX Session
        run: create-session --account ${{ secrets.VTEX_ACCOUNT }} --appkey ${{ secrets.VTEX_APP_KEY }} --apptoken ${{ secrets.VTEX_APP_TOKEN }}

      - name: Prompt for release type
        id: prompt
        run: |
          options=("major" "minor" "patch")
          PS3="Select release type: "
          select opt in "${options[@]}"; do
              echo "::set-output name=release_type::$opt"
              break
          done

      - name: vtex release
        env:
          RELEASE_TYPE: ${{ steps.prompt.outputs.release_type }}
        run: yes Y | vtex release $RELEASE_TYPE

      - name: vtex deploy
        run: yes Y | vtex deploy -f
