name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/brunorodmoreira/cicd-vtex-cli-image:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create VTEX Session
        run: create-session --account ${{ secrets.VTEX_ACCOUNT }} --appkey ${{ secrets.VTEX_APP_KEY }} --apptoken ${{ secrets.VTEX_APP_TOKEN }}

      - name: VTEX Publish
        run: vtex publish

      - name: VTEX deploy
        run: vtex deploy -f -y
