name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/brunorodmoreira/cicd-vtex-cli-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    inputs:
      release-type:
        description: 'The type of release to perform (major, minor, or patch)'
        required: true
        default: 'minor'
        # You can add other validation rules here, such as regex patterns or allowed values.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create VTEX Session
        run: create-session --account ${{ secrets.VTEX_ACCOUNT }} --appkey ${{ secrets.VTEX_APP_KEY }} --apptoken ${{ secrets.VTEX_APP_TOKEN }}

      - name: vtex release
        run: yes Y | vtex release ${{ inputs.release-type }}

      - name: vtex deploy
        run: yes Y | vtex deploy -f
